export const AFFILIATION_CODE_LEN = 6;
export const NORMALSALE_MAX_NFT_HOLD_COUNT = 5;
export const PRESALE_MAX_NFT_HOLD_COUNT = 3;
export const MINT_STATUS = {
    POSSIBLE: 0,
    NOT_WHITELISTED: 1,
    OVERFLOW_MAX_HOLD: 2,
    WAIT_OPENING: 3
};